# Generated by Django 6.0.6 on 2026-06-20 21:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Livestock Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousBidderId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='Bidder', max_length=10)),
                ('letter', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('anonymous_id', models.CharField(max_length=20, unique=True)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_bidders', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['anonymous_id'],
            },
        ),
        migrations.CreateModel(
            name='AntiFraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('self_bid', 'Self-Bidding Attempt'), ('rapid_bids', 'Rapid Consecutive Bids'), ('high_amount', 'Unusually High Bid'), ('price_jump', 'Large Price Jump'), ('duplicate_ip', 'Multiple Accounts Same IP'), ('rate_limit', 'Rate Limit Exceeded'), ('invalid_bid', 'Invalid Bid Amount')], max_length=50)),
                ('description', models.TextField()),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by system (e.g., bid rejected, user blocked)', max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_bid_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('seller_contact_revealed', models.BooleanField(default=False)),
                ('buyer_contact_revealed', models.BooleanField(default=False)),
                ('winner_accepted', models.BooleanField(default=False)),
                ('seller_accepted', models.BooleanField(default=False)),
                ('auction_ended_at', models.DateTimeField()),
                ('winner_announced_at', models.DateTimeField(auto_now_add=True)),
                ('contact_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('deal_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_info', to='auctions.auction')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_sold', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_auctions_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-auction_ended_at'],
            },
        ),
        migrations.CreateModel(
            name='BidAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_winning', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('outbid', 'Outbid'), ('winning', 'Winning'), ('won', 'Won'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livebidding.anonymousbidderid')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_audits', to='auctions.auction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiddingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('total_bids', models.IntegerField(default=0)),
                ('unique_bidders', models.IntegerField(default=0)),
                ('highest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_bidders', models.ManyToManyField(blank=True, related_name='active_bidding_rooms', to=settings.AUTH_USER_MODEL)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_room', to='auctions.auction')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiddingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_auctions_participated', models.IntegerField(default=0)),
                ('total_auctions_won', models.IntegerField(default=0)),
                ('total_bids_placed', models.IntegerField(default=0)),
                ('total_amount_bid', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount_won', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('fraud_flags', models.IntegerField(default=0)),
                ('blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_verified'], name='livebidding_email_i_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='anonymousbidderid',
            index=models.Index(fields=['auction', 'user'], name='livebidding_auction_783f18_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousbidderid',
            index=models.Index(fields=['anonymous_id'], name='livebidding_anonymo_21527b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymousbidderid',
            unique_together={('user', 'auction')},
        ),
        migrations.AddIndex(
            model_name='antifraudlog',
            index=models.Index(fields=['user', 'severity'], name='livebidding_user_id_b016b8_idx'),
        ),
        migrations.AddIndex(
            model_name='antifraudlog',
            index=models.Index(fields=['auction'], name='livebidding_auction_8df4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionwinner',
            index=models.Index(fields=['winner'], name='livebidding_winner__fad390_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionwinner',
            index=models.Index(fields=['seller'], name='livebidding_seller__48b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bidaudit',
            index=models.Index(fields=['auction', 'user'], name='livebidding_auction_2696b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bidaudit',
            index=models.Index(fields=['created_at'], name='livebidding_created_4edc97_idx'),
        ),
        migrations.AddIndex(
            model_name='bidaudit',
            index=models.Index(fields=['status'], name='livebidding_status_370d78_idx'),
        ),
        migrations.AddIndex(
            model_name='biddingroom',
            index=models.Index(fields=['auction', 'is_active'], name='livebidding_auction_48ccbc_idx'),
        ),
    ]
